# Generated by Django 3.2.16 on 2025-06-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkModel',
            new_name='LinkMapped',
        ),
    ]
